import Head from 'next/head';
import styles from '../styles/Home.module.css';
import HeadArticle from '../components/head-articule';
import SquareLink from '../components/square-link';
import IconProject from '../components/icon/project';
import UsersIcon from '../components/icon/users';
import CalculatorIcon from '../components/icon/calculator';

const articles = [
  { url: 'project', text: 'Projectos', icon: IconProject },
  { url: 'client', text: 'Clientes', icon: UsersIcon },
  { url: 'calculator', text: 'Calculdora', icon: CalculatorIcon }
];

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Real State App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <HeadArticle title='Articulo' />
        <div className={styles.grid}>
          {articles.map((article, index) => (
            <SquareLink key={index} url={article.url} text={article.text}>
              <article.icon />
            </SquareLink>
          ))}
        </div>
      </div>
    </div>
  );
}
